name: kas_mini_flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this: Image.assets('assets/images/logo-outlined.png')
  # it's auto included after /images/...
  assets:
    - assets/images/
    - assets/products/